AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Budget for Lambda costs across all regions'

Parameters:
  NotificationEmail:
    Type: String
    Description: Email address to receive budget notifications
    
Resources:
  LambdaBudget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: Lambda-Zero-Global-Budget
        BudgetLimit:
          Amount: "0.01"
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
        CostFilters: 
          Service:
            - Lambda
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 80
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail
